//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoParcial
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesarrolladorProyecto
    {
        public int DesarrolladorProyectoId { get; set; }
        public int DesarrolladorId { get; set; }
        public int ProyectoId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Desarrollador Desarrollador { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
